name: source_server
description: A dart implementation of Source's Query Protocol and RCON from the developer.valvesoftware.com wiki.
version: 3.1.3-dev
homepage: https://github.com/Hexer10/source_server

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.14.2

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.14.2
  lint: ^1.3.0
  test: ^1.17.8
