name: source_server
description: A dart implementation of Source's Query Protocol and RCON from the developer.valvesoftware.com wiki.
version: 3.0.0-dev
homepage: https://github.com/Hexer10/source_query_rcon

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.12.0
  typed_buffer: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.9
  freezed: ^0.12.5
  lint: ^1.3.0