name: source_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://example.com

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.12.0
  typed_buffer: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.4
  freezed: ^0.12.2
  lint: ^1.3.0